### ISSUE TITLE
Getting an IllegalAccessError when I try to create an Entity Manager

### ISSUE THREAD

**Issue by alzoid** [sai-pullabhotla/catatumbo#186]
I am following the quick start guide.  When I try to create the EM I get an error.

I am running this from a Servlet in Appengine Standard.  Any suggestions?  Thank you.

java.lang.IllegalAccessError: tried to access method com.google.cloud.ServiceOptions.getFromServiceLoader(Ljava/lang/Class;Ljava/lang/Object;)Ljava/lang/Object; from class com.google.cloud.http.HttpTransportOptions
	at com.google.cloud.http.HttpTransportOptions.<init>(HttpTransportOptions.java:128)
	at com.google.cloud.http.HttpTransportOptions.<init>(HttpTransportOptions.java:43)
	at com.google.cloud.http.HttpTransportOptions$Builder.build(HttpTransportOptions.java:88)
	at com.jmethods.catatumbo.EntityManagerFactory.getHttpTransportOptions(EntityManagerFactory.java:304)
	at com.jmethods.catatumbo.EntityManagerFactory.createEntityManager(EntityManagerFactory.java:195)
	at com.jmethods.catatumbo.EntityManagerFactory.createDefaultEntityManager(EntityManagerFactory.java:75)
	at com.jmethods.catatumbo.EntityManagerFactory.createDefaultEntityManager(EntityManagerFactory.java:61)
	at ca.aps.wavy.SessionDB.<init>(SessionDB.java:34)
	at ca.aps.wavy.SessionServlet.processRequest(SessionServlet.java:44)
	at ca.aps.wavy.SessionServlet.doGet(SessionServlet.java:73)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:848)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1772)
	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at com.google.apphosting.runtime.jetty9.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:48)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at com.google.apphosting.runtime.jetty9.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:297)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:534)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
	at com.google.apphosting.runtime.jetty9.RpcConnection.handle(RpcConnection.java:202)
	at com.google.apphosting.runtime.jetty9.RpcConnector.serviceRequest(RpcConnector.java:81)
	at com.google.apphosting.runtime.jetty9.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:108)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:680)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:642)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:612)
	at com.google.apphosting.runtime.JavaRuntime$NullSandboxRequestRunnable.run(JavaRuntime.java:806)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:274)
	at java.lang.Thread.run(Thread.java:745)

**Comment by sai-pullabhotla** [comment]
@alzoid - the IllegalAccessError typically means that the class files at runtime are not compatible/different than what the code was compiled with. Would you please double check if your runtime versions of various Jars are compatible with the version of Catatumbo?

**Comment by sai-pullabhotla** [comment]
Closing this due to no response.
