### ISSUE TITLE
@Embedded fields and the Builder pattern

### ISSUE THREAD

**Issue by doctorseus** [sai-pullabhotla/catatumbo#188]
There seems to be a bug with embedded fields when you use the builder pattern to create entities.

If I have a entity with a field annotated with @Embedded and @Exploded (@Imploded works) which uses a Builder class (utilizing the newBuilder() method and an embedded static class) I will get a ClassCastException from my builder to the entity when I want to insert this entity.
It will actually create the entity in the database but the embedded field is missing and it also can't read back the entity.

All of this works if I just use setters and empty constructors directly without the Builder pattern.
If needed I can clarify this a bit more as soon as I have a bit more time, however, I still wanted to report this now. Thanks for all the work!

Exception in thread "main" com.jmethods.catatumbo.EntityManagerException: java.lang.ClassCastException: Cannot cast com.example.Entity$Builder to com.example.Entity
	at com.jmethods.catatumbo.impl.Unmarshaller.initializeEmbedded(Unmarshaller.java:365)
	at com.jmethods.catatumbo.impl.Unmarshaller.unmarshalWithExplodedStrategy(Unmarshaller.java:242)
	at com.jmethods.catatumbo.impl.Unmarshaller.unmarshalEmbeddedFields(Unmarshaller.java:223)
	at com.jmethods.catatumbo.impl.Unmarshaller.unmarshal(Unmarshaller.java:116)
	at com.jmethods.catatumbo.impl.Unmarshaller.unmarshalBaseEntity(Unmarshaller.java:145)
	at com.jmethods.catatumbo.impl.Unmarshaller.unmarshal(Unmarshaller.java:82)
	at com.jmethods.catatumbo.impl.DefaultDatastoreWriter.insert(DefaultDatastoreWriter.java:117)
	at com.jmethods.catatumbo.impl.DefaultEntityManager.insert(DefaultEntityManager.java:175)
	at com.example.DataStoreTest.main(DataStoreTest.java:47)
Caused by: java.lang.ClassCastException: Cannot cast com.example.Entity$Builder to com.example.Entity
	at java.lang.invoke.MethodHandleImpl.newClassCastException(MethodHandleImpl.java:361)
	at java.lang.invoke.MethodHandleImpl.castReference(MethodHandleImpl.java:356)
	at com.jmethods.catatumbo.impl.Unmarshaller.initializeEmbedded(Unmarshaller.java:358)
	... 8 more

**Comment by sai-pullabhotla** [comment]
Thanks for reporting. Would you please post a simple entity and embeddable code to help reproduce?

**Comment by sai-pullabhotla** [comment]
Closing this due to no response.
