### ISSUE TITLE
Add custom mappers

### ISSUE THREAD

**Issue by pierredeman** [sai-pullabhotla/catatumbo#78]
It would be great to add custom mappers to **MapperFactory**.
I'm actually in java8, i would like to ad a custom mapper for **java.time.LocalDateTime** but i'm stuck with the following exception :
>com.jmethods.catatumbo.EntityManagerException: Unknown or unsupported type, class java.time.LocalDateTime, for field time in class com.menkoi.server.module.sample.model.SampleModel. 
	at com.jmethods.catatumbo.impl.IntrospectionUtils.getPropertyMetadata(IntrospectionUtils.java:66)
	at com.jmethods.catatumbo.impl.EntityIntrospector.processField(EntityIntrospector.java:313)
	at com.jmethods.catatumbo.impl.EntityIntrospector.processFields(EntityIntrospector.java:194)
	at com.jmethods.catatumbo.impl.EntityIntrospector.process(EntityIntrospector.java:152)
	at com.jmethods.catatumbo.impl.EntityIntrospector.loadMetadata(EntityIntrospector.java:125)
	at com.jmethods.catatumbo.impl.EntityIntrospector.introspect(EntityIntrospector.java:109)
	at com.jmethods.catatumbo.impl.EntityIntrospector.getEntityListenersMetadata(EntityIntrospector.java:451)
	at com.jmethods.catatumbo.impl.DefaultEntityManager.executeEntityListeners(DefaultEntityManager.java:338)
	at com.jmethods.catatumbo.impl.DefaultDatastoreWriter.insert(DefaultDatastoreWriter.java:112)
	at com.jmethods.catatumbo.impl.DefaultEntityManager.insert(DefaultEntityManager.java:159)
	at com.menkoi.server.module.sample.resource.SampleResource.say(SampleResource.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384)
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
	at java.lang.Thread.run(Thread.java:745)

**Comment by arthur-tse7** [comment]
@pierredeman 
Refer to #72 and #47 . Like @sai-pullabhotla replied to me, you can clone that branch and use it from there. There seems to be a bug with update when working with custom mappers (see #76 ), so take that into consideration.

**Comment by sai-pullabhotla** [comment]
@pierredeman @arthur-tse7 - 

Currently CustomMappers can only be attached to supported types (as defined in the DataType enum). The idea is to override the built-in mapper with a custom mapper. For example, to store enum values in lower case. 

LocalDateTime is not defined in the DataType enum, so the frameworks halts during entity introspection phase. Which is what the exception is. 

I think, we need to get rid of the DataType enum completely and rely on MapperFactory to see if we have a mapper for the specified type. This allows you to use any arbitrary type in the Model class as long as there is mapper to handle the data conversion between model and datastore. I will try to tackle this asap. If either of you are interested in contributing, let me know.

**Comment by sai-pullabhotla** [comment]
@pierredeman - this is now fixed as part of #79. Closing this issue. I'm releasing 1.0.1, which should be available in Maven Central in a few hours.

**Comment by pierredeman** [comment]
Thanks a lot.
